In [3]:
import numpy as np

In [4]:
a =np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])

a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## 3.1 Accessing the element (Row and Column wise)

#### Row and column wise and get an element within matrix 

In [5]:
a[0]

array([1, 2, 3, 4, 5])

In [6]:
a[:,4]

array([ 5, 10])

In [7]:
a[1,2:4]

array([8, 9])

#### Replacement

In [8]:
a[1,2:4]=[9,10]

In [12]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  9, 10, 10]])

## 3.2 Initializing different array

#### All zero matrix

In [15]:
np.zeros((2,3),dtype='int32')

array([[0, 0, 0],
       [0, 0, 0]])

#### All one's matrix

In [19]:
b = np.ones((3,4))

#### Any other value matrix

In [17]:
np.full((2,3),9)

array([[9, 9, 9],
       [9, 9, 9]])

#### use different shape of matrix for any other matrix

In [20]:
np.full_like(b,7)

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [21]:
np.full(b.shape,5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

##### Random number matrix

In [22]:
np.random.rand(4,3)

array([[0.2984128 , 0.33306754, 0.03665133],
       [0.65991542, 0.64386136, 0.3519176 ],
       [0.13287833, 0.02575294, 0.22207677],
       [0.18889972, 0.4427553 , 0.23478856]])

In [24]:
np.random.random_sample(a.shape)

array([[0.0286499 , 0.37891079, 0.48281905, 0.05279781, 0.53519471],
       [0.44882542, 0.28660229, 0.46041366, 0.21548771, 0.54157858]])

##### Random Integer Value

In [31]:
np.random.randint(7,size=(3,3))

array([[3, 6, 0],
       [2, 2, 1],
       [5, 0, 1]])

In [32]:
np.random.randint(3,8,size=(2,3))

array([[3, 3, 6],
       [7, 5, 3]])

##### Identity matrix

In [33]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

##### Repeat an array


In [47]:
p = np.array([[1,2,3]])

q= np.repeat(p,3,axis=0)

##### Use copy

In [55]:
r = q

r[2,2]=7

In [56]:
r

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 7]])

In [57]:
q

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 7]])

In [58]:
#to avoid such issue

r = q.copy()

##### Mathematics function : addition subtraction multiplication division

In [61]:
p = a + 2
print(p)

q = a**2
print(q)

r= a-3
print(r)

j= a/6
print(j)

[[ 3  4  5  6  7]
 [ 8  9 11 12 12]]
[[  1   4   9  16  25]
 [ 36  49  81 100 100]]
[[-2 -1  0  1  2]
 [ 3  4  6  7  7]]
[[0.16666667 0.33333333 0.5        0.66666667 0.83333333]
 [1.         1.16666667 1.5        1.66666667 1.66666667]]


##### Trignometry

In [9]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.41211849, -0.54402111, -0.54402111]])

In [10]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.91113026, -0.83907153, -0.83907153]])

In [11]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501],
       [-0.29100619,  0.87144798, -0.45231566,  0.64836083,  0.64836083]])

##### Linear Algebra

In [17]:
#Matrix Multiplication
a = np.identity(3)

print(a)

b = np.full((3,2),6)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[6 6]
 [6 6]
 [6 6]]


In [19]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.],
       [6., 6.]])

In [21]:
#to calculate determinant

np.linalg.det(a)

1.0

In [ ]:

## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [26]:
np.min(b)

6

In [28]:
np.max(a,axis=0)

array([1., 1., 1.])

In [29]:
np.sum(b,axis=0)

array([18, 18])

##### Recognizing Array

In [31]:
v1 = np.array([1,2,4,9])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 4, 9],
       [5, 6, 7, 8],
       [1, 2, 4, 9],
       [5, 6, 7, 8]])

In [32]:

# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

##### Load data from file

In [45]:
filedata = np.genfromtxt('data.txt',delimiter=',')

filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

##### Boolean Masking and Advance Indexing

In [37]:
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [38]:
filedata[filedata>40]

array([196.,  75.,  42., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [43]:
#index with a lits in numpy

p = np.array([1,2,3,4,5,6,7,8,43,2,4,5])

p[[2,7,8]]

array([ 3,  8, 43])

In [46]:
np.any(filedata >100 ,axis=1)

array([ True,  True,  True])

In [57]:
np.all(filedata<12,axis=0)


array([ True, False, False, False, False, False,  True, False, False,
        True,  True,  True,  True,  True,  True,  True, False, False])

In [53]:
(~((filedata>10)&(filedata <50)))

array([[ True, False, False, False,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True, False, False, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False, False],
       [ True, False, False, False,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [54]:
filedata[(~((filedata>10)&(filedata <50)))]

array([  1., 196.,  75.,   4.,   3.,   6.,   7.,   8.,   0.,   1.,   2.,
         3.,   4.,   5.,   3., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
         4.,   5.,   6.,   7.,   0.,   1., 999.,   2.,   1.,  78.,   0.,
         1.,   2.,   9.,   8.,   7.,   1.,  76.,  88.])